### ISSUE TITLE
Error : Connection timed out (Errno::ETIMEDOUT)

### ISSUE THREAD

**Issue by jnak** [bpoweski/apnserver#6]
Hi guys,

I've been noticing something strange lately. After some time idle (no notification is pushed), ApnServer fails silently to deliver notifications, and end up raising : 

```
/usr/lib/ruby/1.9.1/openssl/buffering.rb:235:in `syswrite': Connection timed out (Errno::ETIMEDOUT)
    from /usr/lib/ruby/1.9.1/openssl/buffering.rb:235:in `do_write'
    from /usr/lib/ruby/1.9.1/openssl/buffering.rb:249:in `write'
    from /somepath/shared/bundled_gems/ruby/1.9.1/bundler/gems/apnserver-88e2c873487a/lib/apnserver/client.rb:36:in `write'
```

I'll be looking into it, but before, I'd like to know if it s specific to my setup or if some of you ever experienced the same issue. 

Cheers

**Comment by thermogl** [comment]
You ever manage to resolve this issue? I'm seeing the same thing.

**Comment by jnak** [comment]
What I do is that I force a reconnection after being idle for 10 minutes.
It's not superclean but at least it does the job pretty well. If you find something cleaner, let me know

**Comment by thermogl** [comment]
Dang, I was hoping for something cleaner (like you said).

I'll keep looking and post back if I find anything.

Thanks.
